id: "default"
name: Monokai Pro
# all colors were pulled from the official vscode extension
colors:
  # primary colors
  red: "#ff6188"
  orange: "#fc9867"
  yellow: "#ffd866"
  green: "#a9dc76"
  blue: "#78dce8"
  purple: "#ab9df2"
  # base colors, sorted from darkest to lightest
  base0: "#19181a"
  base1: "#221f22"
  base2: "#2d2a2e"
  base3: "#403e41"
  base4: "#5b595c"
  base5: "#727072"
  base6: "#939293"
  base7: "#c1c0c0"
  base8: "#fcfcfa"
  # variants (for when transparency isn't supported)
  base8x0c: "#363337" # using base2 as bg
