id: "default"
name: Monokai Pro
# all colors were pulled from the official vscode extension
colors:
  # primary colors
  red: "#ff6188"
  errorRed: "#990909"
  orange: "#fc9867"
  yellow: "#ffd866"
  darkYellow: "#d7a916"
  green: "#a9dc76"
  darkGreen: "#117e00"
  blue: "#78dce8"
  darkBlue: "#0050bb"
  purple: "#ab9df2"
  # base colors, sorted from darkest to lightest
  base0: "#120f13"
  base1: "#221d23"
  base2: "#251f26"
  base3: "#2d2a2e"
  base4: "#322e33"
  base5: "#403b41"
  base6: "#605f62"
  base7: "#727072"
  base8: "#939293"
  base9: "#aba5ab"
  base10: "#cecec3"
  base11: "#fcfcfa"
  # variants (for when transparency isn't supported)
  base8x0c: "#363337" # using base2 as bg
